### PR TITLE
Fix file headers + typos + whitespace

### PR DESCRIPTION
**Pull request by luzpaz**
- Modified copyright comment block the way Werner has does it
- Fixed typos
- Fixed whitespace

### CODE REVIEW

**Comment by joelgraff** [comment]
Looks fantastic!  Thanks!

**Comment by joelgraff** [comment]
Probably a good idea.

**Comment by luzpaz** [comment]
@microelly2 ping

**Comment by joelgraff** [comment]
Just realized that the code comment syntax is invalid when I merged my local repo with github and suddenly everything broke!

You can't do multi-line comments in Python with /* */.  The only way to do it is with triple quotes, which are reserved for doc strings...  So the fix is to use single-line hash marks.

I should have caught that - but I don't write enough python. ;)

**Pull request merged**
